name: "cobain"
fs:
  url: "/tmp/es"
  update_rate: "5m"
  json_support: false
  filename_as_id: true
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: true
  index_content: true
  attributes_support: false
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: false

elasticsearch:
  nodes:
  - url: "http://elasticsearch:9200"
  # index: "docs"
  bulk_size: 1000
  flush_interval: "5s"
  byte_size: "10mb"